preset: laravel

risky: false

linting: true

finder:
  exclude:
    - "wordpress"
    - "tests"
    - "storage"
    - "resources"
    - "public"
  name:
    - "*.php"
  path:
    - "app"
    - "bootstrap"
    - "config"
    - "database"
    - "database"
