preset: laravel

risky: false

linting: true

finder:
  exclude:
    - "tests"
    - "storage"
    - "resources/assets"
    - "resources/views"
    - "resources/pages"
    - "public"
  name:
    - "*.php"
  path:
    - "app"
    - "bootstrap"
    - "config"
    - "database"
    - "resources/lang"
